import { NextRequest, NextResponse } from "next/server";
import { Result } from "@/app/models/Result";
import ollama from "ollama";
import { Recipe } from "@/app/models/Recipe";
import { getSession } from "@/lib/neo4j";

export async function POST(request: NextRequest) {
  let messagetoEmbed: string;
  let message;
  let personName: string;

  try {
    const formData = await request.formData();
    const image = formData.get("image") as File;

    message = formData.get("message") as string;
    messagetoEmbed = message;

    if (image) {
      const arrayBuffer = await image.arrayBuffer();
      const uint8Array = new Uint8Array(arrayBuffer);
      const images = [uint8Array];

      const generateResponse = await ollama.generate({
        model: "foodie",
        prompt:
          "Try to guess the food on this image. Do not detail the plating, aesthetics focus only on the food and what it could be made of.",
        images,
      });
      messagetoEmbed += " " + generateResponse.response;
    }
  } catch (error) {
    console.error("Error handling form data:", error);
    return NextResponse.json(
      { error: "Error handling form data" },
      { status: 500 }
    );
  }

  try {
    const embeddingsResponse = await ollama.embeddings({
      model: "all-minilm",
      prompt: messagetoEmbed,
    });

    const embeddedMessage = embeddingsResponse.embedding;
    let records;

    try {
      const generatedQuery = await ollama.generate({
        model: "cypherExpert",
        prompt: `Please generate a Cypher query to match this:${JSON.stringify(
          message
        )} Only use the nodes and relationships defined above. Do not invent any new relationships or nodes or values that were explicitly mentioned. Do not include a RETURN statement, as the query will be injected into a larger query. Only generate the MATCH or WHERE clauses and preapare the result of the query (recipes) in a variable named \"r\" so that the query can be injected.`,
      });
      let query = generatedQuery.response
        .replace(/(^["“”]|["“”]$)/g, "") // Replace double curly quotes and straight quotes at the start/end
        .replace(/["“”]/g, "'") // Replace all double curly quotes and straight quotes inside
        .replace(/[‘’]/g, "'"); // Replace all single curly quotes

      // Append a single quote if the count of single quotes is odd
      query += (query.match(/'/g) || []).length % 2 !== 0 ? "'" : "";
      if (
        query.includes("MATCH (p:Person") &&
        (query.includes(":LOVES") ||
          query.includes(":HATES") ||
          query.includes(":IS_ALLERGIC_TO"))
      ) {
        // Extract the person's name from the query
        personName = extractPersonName(query);
      }

      console.log("generated query:" + query);
      // Step 2: Run the LLM-generated query with embedding-based filtering.
      //first vector search, then filter out results generated by the llm
      const embeddedQuery = `
       // Apply LLM-generated filtering if the query exists
   ${query ? `${query}` : "MATCH (recipe:Recipe)"}

   // Standardize the recipe variable for the next part of the query
   WITH r AS recipe

   // Run embedding-based search only on the filtered results
   CALL db.index.vector.queryNodes('embedding_index', 20, $embeddedMessage)
   YIELD node AS recipeFromEmbedding, score

   // Ensure the filtered recipes are ordered by embedding-based score
   WHERE recipe = recipeFromEmbedding

   RETURN DISTINCT recipe AS RecipeResult, score
   ORDER BY score DESC
   LIMIT 3;
     `;

      // Log the full query to the console, including the dynamically generated part
      console.log("Full Query with LLM-generated part:", embeddedQuery);

      // Execute the query

      const session = getSession();
      const result = await session.run(embeddedQuery, { embeddedMessage });
      records = result.records;
      console.log("records are:" + records);
      // TODO if no records, do simple vector search
      if (!records || records.length === 0) {
        records = await performVectorSearch(embeddedMessage);
      }
    } catch (error) {
      console.error(
        "Error with LLM query, falling back to vector search:",
        error
      );

      // Fallback: Simple vector search without the LLM-generated filtering.
      records = await performVectorSearch(embeddedMessage);
    } finally {
      await getSession().close();
    }

    const data = records.map((record) => ({
      id: record.get("RecipeResult").properties.id.low,
      name: record.get("RecipeResult").properties.name,
      imageurl: record.get("RecipeResult").properties.imageUrl,
      cooktime: record.get("RecipeResult").properties.cookTime.low,
      cuisine: record.get("RecipeResult").properties.cuisine,
      serves: record.get("RecipeResult").properties.serves.low,
      description: record.get("RecipeResult").properties.description,
    }));

    console.log("data is:" + data);
    const detailedRecipes = await Promise.all(
      data.map(async (recipe: Recipe) => {
        const generateTags = await ollama.generate({
          model: "foodie",
          prompt: `Generate exactly 3 tags that represent this recipe: ${JSON.stringify(
            recipe
          )}, separated by comma. Do not use # for the tags. The 3 tags should not be ingredients of the recipes.`,
        });

        const tags = generateTags.response.split(",").map((tag) => tag.trim());

        return { ...recipe, tags };
      })
    );

    const result: Result = {
      recipes: detailedRecipes,
      inputText: messagetoEmbed,
      recommendedFor: personName,
    };
    return NextResponse.json(result);
  } catch (error) {
    console.error("Error generating embeddings or fetching recipes:", error);
    return NextResponse.json(
      { error: "Error generating embeddings or fetching recipes" },
      { status: 500 }
    );
  }
}

function extractPersonName(generatedQuery: string): string | null {
  // Use a regular expression to find the name of the person inside the query
  const personMatch = generatedQuery.match(
    /MATCH\s*\(p:Person\s*{name:\s*['"](\w+)['"]}/i
  );

  // If a match is found, return the person's name
  if (personMatch && personMatch.length > 1) {
    return personMatch[1];
  }

  // If no match is found, return null
  return null;
}

async function performVectorSearch(embeddedMessage: number[]): Promise<any> {
  let records;
  try {
    const session = getSession();
    const fallbackResult = await session.run(
      `WITH $embeddedMessage AS embeddedMessage
 CALL db.index.vector.queryNodes('embedding_index', 5, embeddedMessage)
 YIELD node AS recipe, score
 WITH recipe, score
 ORDER BY score DESC
 RETURN DISTINCT recipe AS RecipeResult
 LIMIT 3;`,
      { embeddedMessage }
    );
    records = fallbackResult.records;
    console.log("fallback records are:" + records);
    return records;
  } catch (fallbackError) {
    console.error("Error during fallback vector search:", fallbackError);
    return NextResponse.json(
      { error: "Failed to generate recommendations with fallback." },
      { status: 500 }
    );
  }
}
